server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/upccinema?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

logging:
  level:
   root: warn
   com.cinema.tickets_selling.dao: trace
  pattern:
    console: '%p%m%n'